#!/usr/bin/env bash

set -euo pipefail

# Temporal variables for the installation to work, once dotfiles are installed, those are exported and available
# everywhere.
export DOTFILES_PATH="$HOME/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export DOTLY_ENV=PROD
export DOTLY_INSTALLER=true

# Installation

# Clone dotfiles repository
git clone https://github.com/d-asensio/dotfiles "$HOME/.dotfiles"

# Go to dotfiles folder
cd "$DOTFILES_PATH"

# Install git submodules
git submodule update --init --recursive

# Install dotfiles
"$DOTLY_PATH/bin/dot" self install

# Source bash config
source ~/.bashrc

# Reset brew to ensure a fresh installation
brew update-reset

# Import packages
dot package import
