#!/usr/bin/env bash

# Wait until the processes have been shut down
# while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

# Start polybar
polybar --reload example -c $HOME/.config/polybar/config &
